trigger:
- main

resources:
- repo: self

variables:
    imageRepository: 'becadocker'
    containerRegistry: 'becacontainerregistry.azurecr.io'
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: '$(Build.BuildId)'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: $(vmImageName)
  steps:
  - script: |
      docker login $(containerRegistry) -u $(dockerId) -p $(dockerPassword)
      docker build -t $(containerRegistry)/$(imageRepository):$(tag) -f $(dockerfilePath) .
      docker push $(containerRegistry)/$(imageRepository):$(tag)
    displayName: Build and push an image to container registry
    env:
      dockerId: $(dockerId)
      dockerPassword: $(dockerPassword)
